apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontend-netpol
  labels:
    app: frontend-ui
spec:
  podSelector:
    matchLabels:
      app: frontend-ui
  policyTypes:
  - Ingress
  ingress:
  - ports:
    - protocol: TCP
      port: {{ .Values.service.targetPort }}
