apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: frontend-ui
  labels:
    app: frontend-ui
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    {{- toYaml .Values.rollout.strategy | nindent 4 }}
  selector:
    matchLabels:
      app: frontend-ui
  template:
    metadata:
      labels:
        app: frontend-ui
    spec:
      containers:
        - name: frontend-ui
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
