apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-stack
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 2.10.2
    chart: loki-stack
    helm:
      valueFiles:
      - $values/apps/logging/loki-stack-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      targetRevision: 2.10.2
      chart: loki-stack
      helm:
        valueFiles:
        - $values/apps/logging/loki-stack-values.yaml
    - repoURL: https://github.com/eranlebovic/final_project.git
      targetRevision: HEAD
      ref: values
