apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 69.8.2
    chart: kube-prometheus-stack
    helm:
      valueFiles:
      - $values/apps/monitoring/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  # This section allows referencing another repo (our git repo) for values files
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 69.8.2
      chart: kube-prometheus-stack
      helm:
        valueFiles:
        - $values/apps/monitoring/values.yaml
    - repoURL: https://github.com/eranlebovic/final_project.git
      targetRevision: HEAD
      ref: values
